spring:
  application:
    name: accounts-composite-service
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://ip-172-31-4-219.ec2.internal:8080/

info:
  component: Accounts Composite Service
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://ip-172-31-14-33.ec2.internal:8080/eureka
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'
