spring:
  profiles:
    active: cloud
  application:
    name: oauth2-jwt-identity-server
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://sansoft-spring-cloud-config-server.us-east-1.elasticbeanstalk.com/

info:
  component: Oauth2 JWT Authentication Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  user:
    password: password
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'