spring:
  profiles:
    active: cloud
  application:
    name: products-composite-service
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://172.31.6.132/
#      uri: http://localhost:8888       
      
#server:
#  port: 8087

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
info:
  component: Products Composite Service

eureka:
  name: products-composite-service
  awsAccessId: AKIAIXPIFMO634VRHDWA
  awsSecretKey: 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
  preferSameZone: true
  shouldUseDns: true
  serviceUrl:
    default: http://172.31.12.87/eureka
  client:
    region: us-east-1
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://172.31.12.87/eureka
      us-east-1a: http://172.31.12.87/eureka
  us-east-1:
      availabilityZones: us-east-1a
  instance:
    hostname: ip-172-31-14-136.ec2.internal
    non-secure-port: 80
    ip-address: 172-31-14-136
    prefer-ip-address: true
    virtual-host-name: ec2-52-87-167-186.compute-1.amazonaws.com
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    app-group-name: micro-service
    appname: products-composite-service 
 #   metadataMap:
 #     instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'