spring:
  profiles:
    active: cloud
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      server:
        git:
          uri: https://github.com/sanjeeb-talukdar/microservices-demo-config-repo.git
  application:
    name: spring-cloud-config-server    
  
info:
  component: String Cloud Config Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://sansoft-eureka-discovery-server.us-east-1.elasticbeanstalk.com/eureka
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'     