spring:
  profiles:
    active: cloud
  application:
    name: transactions-core-service
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      uri: http://ip-172-31-2-81.ec2.internal:8080/
            
info:
  component: Transactions Core Service
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://ip-172-31-11-75.ec2.internal:8080/eureka
      
logging:
  level:
    ROOT: 'ERROR'
    org.springframework.web: 'ERROR'
    org.springframework.cloud: 'ERROR'
    org.springframework.boot: 'ERROR'
    org.springframework: 'ERROR'